import type { Metadata } from 'next'
import styles from './layout.module.scss'

import { Varela_Round } from 'next/font/google'
 
const varela = Varela_Round({weight: '400'})

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={[varela.className, styles.body].join(' ')}>
        {children}
      </body>
    </html>
  )
}
 